version: "3"
services:
  front-end:
    build: .
    container_name: weather-frontend
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 1313:8080
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - front-end